<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Solutions | Bayesian Analysis of Employee Productivity</title>
  <meta name="description" content="Chapter 9 Solutions | Bayesian Analysis of Employee Productivity" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Solutions | Bayesian Analysis of Employee Productivity" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Solutions | Bayesian Analysis of Employee Productivity" />
  
  
  

<meta name="author" content="AbdulHafiz Abba" />


<meta name="date" content="2024-12-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exercise-description.html"/>
<link rel="next" href="the-pool-of-tears.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bayesian Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction to Statistical Frameworks</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#classical-framework"><i class="fa fa-check"></i><b>1.2</b> Classical Framework</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#key-principles-of-the-classical-framework"><i class="fa fa-check"></i><b>1.2.1</b> Key Principles of the Classical Framework</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#tools-of-the-classical-framework"><i class="fa fa-check"></i><b>1.2.2</b> Tools of the Classical Framework</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#example-testing-a-coins-fairness"><i class="fa fa-check"></i><b>1.2.3</b> Example: Testing a Coin’s Fairness</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#frequentist-framework"><i class="fa fa-check"></i><b>1.3</b> Frequentist Framework</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#key-principles-of-the-frequentist-framework"><i class="fa fa-check"></i><b>1.3.1</b> Key Principles of the Frequentist Framework</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#frequentist-tools"><i class="fa fa-check"></i><b>1.3.2</b> Frequentist Tools</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#example-estimating-the-mean"><i class="fa fa-check"></i><b>1.3.3</b> Example: Estimating the Mean</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#bayesian-framework"><i class="fa fa-check"></i><b>1.4</b> Bayesian Framework</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#key-principles-of-the-bayesian-framework"><i class="fa fa-check"></i><b>1.4.1</b> Key Principles of the Bayesian Framework</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#bayes-theorem"><i class="fa fa-check"></i><b>1.4.2</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#example-estimating-the-probability-of-rain"><i class="fa fa-check"></i><b>1.4.3</b> Example: Estimating the Probability of Rain</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#comparison-of-frameworks"><i class="fa fa-check"></i><b>1.5</b> Comparison of Frameworks</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html"><i class="fa fa-check"></i><b>2</b> Conditional Probability and Bayes’ Theorem</a>
<ul>
<li class="chapter" data-level="2.1" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#conditional-probability"><i class="fa fa-check"></i><b>2.1</b> Conditional Probability</a></li>
<li class="chapter" data-level="2.2" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#bayes-theorem-1"><i class="fa fa-check"></i><b>2.2</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="2.3" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#worked-example-1-disease-diagnosis"><i class="fa fa-check"></i><b>2.3</b> Worked Example 1: Disease Diagnosis</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#solution"><i class="fa fa-check"></i><b>2.3.1</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#worked-example-2-spam-email-classification"><i class="fa fa-check"></i><b>2.4</b> Worked Example 2: Spam Email Classification</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#solution-1"><i class="fa fa-check"></i><b>2.4.1</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="conditional-probability-and-bayes-theorem.html"><a href="conditional-probability-and-bayes-theorem.html#summary"><i class="fa fa-check"></i><b>2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html"><i class="fa fa-check"></i><b>3</b> Common Probability Distributions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#bernoulli-distribution"><i class="fa fa-check"></i><b>3.1</b> Bernoulli Distribution</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#probability-mass-function-pmf"><i class="fa fa-check"></i><b>3.1.1</b> Probability Mass Function (PMF)</a></li>
<li class="chapter" data-level="3.1.2" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#mean-and-variance"><i class="fa fa-check"></i><b>3.1.2</b> Mean and Variance</a></li>
<li class="chapter" data-level="3.1.3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#cumulative-distribution-function-cdf"><i class="fa fa-check"></i><b>3.1.3</b> Cumulative Distribution Function (CDF)</a></li>
<li class="chapter" data-level="3.1.4" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-1-biased-coin-toss"><i class="fa fa-check"></i><b>3.1.4</b> Worked Example 1: Biased Coin Toss</a></li>
<li class="chapter" data-level="3.1.5" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-2-quality-control"><i class="fa fa-check"></i><b>3.1.5</b> Worked Example 2: Quality Control</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#uniform-distribution"><i class="fa fa-check"></i><b>3.2</b> Uniform Distribution</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#probability-density-function-pdf"><i class="fa fa-check"></i><b>3.2.1</b> Probability Density Function (PDF)</a></li>
<li class="chapter" data-level="3.2.2" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#mean-and-variance-1"><i class="fa fa-check"></i><b>3.2.2</b> Mean and Variance</a></li>
<li class="chapter" data-level="3.2.3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#cumulative-distribution-function-cdf-1"><i class="fa fa-check"></i><b>3.2.3</b> Cumulative Distribution Function (CDF)</a></li>
<li class="chapter" data-level="3.2.4" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-1-random-number-generator"><i class="fa fa-check"></i><b>3.2.4</b> Worked Example 1: Random Number Generator</a></li>
<li class="chapter" data-level="3.2.5" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-2-waiting-time"><i class="fa fa-check"></i><b>3.2.5</b> Worked Example 2: Waiting Time</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#exponential-distribution"><i class="fa fa-check"></i><b>3.3</b> Exponential Distribution</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#understanding-exponential-distribution"><i class="fa fa-check"></i><b>3.3.1</b> Understanding Exponential Distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#example-waiting-for-a-bus"><i class="fa fa-check"></i><b>3.4</b> Example: Waiting for a Bus</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#key-ideas"><i class="fa fa-check"></i><b>3.4.1</b> Key Ideas:</a></li>
<li class="chapter" data-level="3.4.2" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#simple-shape"><i class="fa fa-check"></i><b>3.4.2</b> Simple Shape:</a></li>
<li class="chapter" data-level="3.4.3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#why-its-useful"><i class="fa fa-check"></i><b>3.4.3</b> Why It’s Useful:</a></li>
<li class="chapter" data-level="3.4.4" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#probability-density-function-pdf-1"><i class="fa fa-check"></i><b>3.4.4</b> Probability Density Function (PDF)</a></li>
<li class="chapter" data-level="3.4.5" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#mean-and-variance-2"><i class="fa fa-check"></i><b>3.4.5</b> Mean and Variance</a></li>
<li class="chapter" data-level="3.4.6" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#cumulative-distribution-function-cdf-2"><i class="fa fa-check"></i><b>3.4.6</b> Cumulative Distribution Function (CDF)</a></li>
<li class="chapter" data-level="3.4.7" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-1-time-between-phone-calls"><i class="fa fa-check"></i><b>3.4.7</b> Worked Example 1: Time Between Phone Calls</a></li>
<li class="chapter" data-level="3.4.8" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-2-machine-failure-time"><i class="fa fa-check"></i><b>3.4.8</b> Worked Example 2: Machine Failure Time</a></li>
<li class="chapter" data-level="3.4.9" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#step-1-key-information"><i class="fa fa-check"></i><b>3.4.9</b> Step 1: Key Information</a></li>
<li class="chapter" data-level="3.4.10" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#step-2-r-code-for-calculations"><i class="fa fa-check"></i><b>3.4.10</b> Step 2: R Code for Calculations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#normal-distribution"><i class="fa fa-check"></i><b>3.5</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#probability-density-function-pdf-2"><i class="fa fa-check"></i><b>3.5.1</b> Probability Density Function (PDF)</a></li>
<li class="chapter" data-level="3.5.2" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#mean-and-variance-3"><i class="fa fa-check"></i><b>3.5.2</b> Mean and Variance</a></li>
<li class="chapter" data-level="3.5.3" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#cumulative-distribution-function-cdf-3"><i class="fa fa-check"></i><b>3.5.3</b> Cumulative Distribution Function (CDF)</a></li>
<li class="chapter" data-level="3.5.4" data-path="common-probability-distributions.html"><a href="common-probability-distributions.html#worked-example-1-exam-scores"><i class="fa fa-check"></i><b>3.5.4</b> Worked Example 1: Exam Scores</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-beta-distribution.html"><a href="the-beta-distribution.html"><i class="fa fa-check"></i><b>4</b> The Beta Distribution</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-beta-distribution.html"><a href="the-beta-distribution.html#definition"><i class="fa fa-check"></i><b>4.1</b> Definition</a></li>
<li class="chapter" data-level="4.2" data-path="the-beta-distribution.html"><a href="the-beta-distribution.html#properties"><i class="fa fa-check"></i><b>4.2</b> Properties</a></li>
<li class="chapter" data-level="4.3" data-path="the-beta-distribution.html"><a href="the-beta-distribution.html#shape-of-the-distribution"><i class="fa fa-check"></i><b>4.3</b> Shape of the Distribution</a></li>
<li class="chapter" data-level="4.4" data-path="the-beta-distribution.html"><a href="the-beta-distribution.html#worked-example"><i class="fa fa-check"></i><b>4.4</b> Worked Example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bayesian-inference.html"><a href="bayesian-inference.html"><i class="fa fa-check"></i><b>5</b> Bayesian Inference</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bayesian-inference.html"><a href="bayesian-inference.html#bayes-theorem-2"><i class="fa fa-check"></i><b>5.1</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="5.2" data-path="bayesian-inference.html"><a href="bayesian-inference.html#worked-example-determining-if-a-coin-is-loaded"><i class="fa fa-check"></i><b>5.2</b> Worked Example: Determining if a Coin is Loaded</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bayesian-inference.html"><a href="bayesian-inference.html#problem-statement"><i class="fa fa-check"></i><b>5.2.1</b> Problem Statement</a></li>
<li class="chapter" data-level="5.2.2" data-path="bayesian-inference.html"><a href="bayesian-inference.html#step-by-step-solution"><i class="fa fa-check"></i><b>5.2.2</b> Step-by-step Solution</a></li>
<li class="chapter" data-level="5.2.3" data-path="bayesian-inference.html"><a href="bayesian-inference.html#conclusion"><i class="fa fa-check"></i><b>5.2.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="bayesian-inference.html"><a href="bayesian-inference.html#worked-example-1"><i class="fa fa-check"></i><b>5.3</b> Worked Example</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-beta-prior-distribution.html"><a href="the-beta-prior-distribution.html"><i class="fa fa-check"></i><b>6</b> The Beta Prior Distribution</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-beta-prior-distribution.html"><a href="the-beta-prior-distribution.html#concept"><i class="fa fa-check"></i><b>6.1</b> Concept</a></li>
<li class="chapter" data-level="6.2" data-path="the-beta-prior-distribution.html"><a href="the-beta-prior-distribution.html#worked-example-bayesian-updating"><i class="fa fa-check"></i><b>6.2</b> Worked Example: Bayesian Updating</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="posterior-interval.html"><a href="posterior-interval.html"><i class="fa fa-check"></i><b>7</b> Posterior Interval</a>
<ul>
<li class="chapter" data-level="7.1" data-path="posterior-interval.html"><a href="posterior-interval.html#definition-1"><i class="fa fa-check"></i><b>7.1</b> Definition</a></li>
<li class="chapter" data-level="7.2" data-path="posterior-interval.html"><a href="posterior-interval.html#interpretation"><i class="fa fa-check"></i><b>7.2</b> Interpretation</a></li>
<li class="chapter" data-level="7.3" data-path="posterior-interval.html"><a href="posterior-interval.html#worked-example-posterior-interval-for-a-coin-toss"><i class="fa fa-check"></i><b>7.3</b> Worked Example: Posterior Interval for a Coin Toss</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="posterior-interval.html"><a href="posterior-interval.html#problem-statement-1"><i class="fa fa-check"></i><b>7.3.1</b> Problem Statement</a></li>
<li class="chapter" data-level="7.3.2" data-path="posterior-interval.html"><a href="posterior-interval.html#step-1-compute-the-posterior-interval"><i class="fa fa-check"></i><b>7.3.2</b> Step 1: Compute the Posterior Interval</a></li>
<li class="chapter" data-level="7.3.3" data-path="posterior-interval.html"><a href="posterior-interval.html#step-2-quantile-calculation-using-r-or-python"><i class="fa fa-check"></i><b>7.3.3</b> Step 2: Quantile Calculation (Using R or Python)</a></li>
<li class="chapter" data-level="7.3.4" data-path="posterior-interval.html"><a href="posterior-interval.html#conclusion-1"><i class="fa fa-check"></i><b>7.3.4</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exercise-description.html"><a href="exercise-description.html"><i class="fa fa-check"></i><b>8</b> Exercise Description</a></li>
<li class="chapter" data-level="9" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>9</b> Solutions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="solutions.html"><a href="solutions.html#parameters-of-interest"><i class="fa fa-check"></i><b>9.1</b> 1. Parameters of Interest</a></li>
<li class="chapter" data-level="9.2" data-path="solutions.html"><a href="solutions.html#likelihood"><i class="fa fa-check"></i><b>9.2</b> 2. Likelihood</a></li>
<li class="chapter" data-level="9.3" data-path="solutions.html"><a href="solutions.html#prior"><i class="fa fa-check"></i><b>9.3</b> 3. Prior</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="solutions.html"><a href="solutions.html#types-of-priors"><i class="fa fa-check"></i><b>9.3.1</b> 2. Types of Priors</a></li>
<li class="chapter" data-level="9.3.2" data-path="solutions.html"><a href="solutions.html#the-conjugate-prior-is-a-beta-prior.-plot-the-density-with-dbeta."><i class="fa fa-check"></i><b>9.3.2</b> The conjugate prior is a beta prior. Plot the density with dbeta.</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="solutions.html"><a href="solutions.html#prior-probabilities"><i class="fa fa-check"></i><b>9.4</b> 4. Prior Probabilities</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="solutions.html"><a href="solutions.html#probabilities-and-their-meanings"><i class="fa fa-check"></i><b>9.4.1</b> Probabilities and Their Meanings</a></li>
<li class="chapter" data-level="9.4.2" data-path="solutions.html"><a href="solutions.html#summary-1"><i class="fa fa-check"></i><b>9.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="solutions.html"><a href="solutions.html#types-of-gamma-priors"><i class="fa fa-check"></i><b>9.5</b> Types of Gamma Priors</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="solutions.html"><a href="solutions.html#non-informative-or-weak-priors"><i class="fa fa-check"></i><b>9.5.1</b> 1. Non-Informative or Weak Priors</a></li>
<li class="chapter" data-level="9.5.2" data-path="solutions.html"><a href="solutions.html#informative-priors"><i class="fa fa-check"></i><b>9.5.2</b> 2. Informative Priors</a></li>
<li class="chapter" data-level="9.5.3" data-path="solutions.html"><a href="solutions.html#weakly-informative-priors"><i class="fa fa-check"></i><b>9.5.3</b> 3. Weakly Informative Priors</a></li>
<li class="chapter" data-level="9.5.4" data-path="solutions.html"><a href="solutions.html#hierarchical-priors"><i class="fa fa-check"></i><b>9.5.4</b> 4. Hierarchical Priors</a></li>
<li class="chapter" data-level="9.5.5" data-path="solutions.html"><a href="solutions.html#empirical-priors"><i class="fa fa-check"></i><b>9.5.5</b> 5. Empirical Priors</a></li>
<li class="chapter" data-level="9.5.6" data-path="solutions.html"><a href="solutions.html#special-case-priors"><i class="fa fa-check"></i><b>9.5.6</b> 6. Special Case Priors</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="solutions.html"><a href="solutions.html#visualizing-gamma-priors-in-r"><i class="fa fa-check"></i><b>9.6</b> Visualizing Gamma Priors in R</a></li>
<li class="chapter" data-level="9.7" data-path="solutions.html"><a href="solutions.html#example-2-gamma-distribution---modeling-call-center-wait-times"><i class="fa fa-check"></i><b>9.7</b> Example 2: Gamma Distribution - Modeling Call Center Wait Times</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="solutions.html"><a href="solutions.html#scenario"><i class="fa fa-check"></i><b>9.7.1</b> Scenario</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="solutions.html"><a href="solutions.html#gamma-distribution-modeling-call-center-wait-times"><i class="fa fa-check"></i><b>9.8</b> Gamma Distribution: Modeling Call Center Wait Times</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="solutions.html"><a href="solutions.html#problem-description"><i class="fa fa-check"></i><b>9.8.1</b> Problem Description</a></li>
<li class="chapter" data-level="9.8.2" data-path="solutions.html"><a href="solutions.html#solution-2"><i class="fa fa-check"></i><b>9.8.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="solutions.html"><a href="solutions.html#example-2-normal-distribution---analyzing-employee-productivity"><i class="fa fa-check"></i><b>9.9</b> Example 2: Normal Distribution - Analyzing Employee Productivity</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="solutions.html"><a href="solutions.html#questions"><i class="fa fa-check"></i><b>9.9.1</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="solutions.html"><a href="solutions.html#solution-3"><i class="fa fa-check"></i><b>9.10</b> Solution</a>
<ul>
<li class="chapter" data-level="9.10.1" data-path="solutions.html"><a href="solutions.html#step-1-posterior-distribution-1"><i class="fa fa-check"></i><b>9.10.1</b> Step 1: Posterior Distribution</a></li>
<li class="chapter" data-level="9.10.2" data-path="solutions.html"><a href="solutions.html#step-2-r-code-to-compute-posterior-parameters"><i class="fa fa-check"></i><b>9.10.2</b> Step 2: R Code to Compute Posterior Parameters</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="solutions.html"><a href="solutions.html#linear-regression"><i class="fa fa-check"></i><b>9.11</b> Linear regression</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="solutions.html"><a href="solutions.html#classical-vs.-bayesian-linear-regression"><i class="fa fa-check"></i><b>9.11.1</b> Classical vs. Bayesian Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="solutions.html"><a href="solutions.html#bayesian-linear-regression-framework"><i class="fa fa-check"></i><b>9.12</b> Bayesian Linear Regression Framework</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="solutions.html"><a href="solutions.html#model-specification"><i class="fa fa-check"></i><b>9.12.1</b> Model Specification</a></li>
<li class="chapter" data-level="9.12.2" data-path="solutions.html"><a href="solutions.html#bayesian-framework-1"><i class="fa fa-check"></i><b>9.12.2</b> Bayesian Framework</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="solutions.html"><a href="solutions.html#example-bayesian-linear-regression-in-r"><i class="fa fa-check"></i><b>9.13</b> Example: Bayesian Linear Regression in R</a>
<ul>
<li class="chapter" data-level="9.13.1" data-path="solutions.html"><a href="solutions.html#problem-setup"><i class="fa fa-check"></i><b>9.13.1</b> Problem Setup</a></li>
<li class="chapter" data-level="9.13.2" data-path="solutions.html"><a href="solutions.html#posterior-analysis"><i class="fa fa-check"></i><b>9.13.2</b> Posterior Analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.14" data-path="solutions.html"><a href="solutions.html#interpretation-1"><i class="fa fa-check"></i><b>9.14</b> Interpretation</a></li>
<li class="chapter" data-level="9.15" data-path="solutions.html"><a href="solutions.html#advantages-of-bayesian-linear-regression"><i class="fa fa-check"></i><b>9.15</b> Advantages of Bayesian Linear Regression</a></li>
<li class="chapter" data-level="9.16" data-path="solutions.html"><a href="solutions.html#conclusion-2"><i class="fa fa-check"></i><b>9.16</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-pool-of-tears.html"><a href="the-pool-of-tears.html"><i class="fa fa-check"></i><b>10</b> The pool of tears</a></li>
<li class="chapter" data-level="11" data-path="a-caucus-race-and-a-long-tale.html"><a href="a-caucus-race-and-a-long-tale.html"><i class="fa fa-check"></i><b>11</b> A caucus-race and a long tale</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bayesian Analysis of Employee Productivity</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="solutions" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Solutions<a href="solutions.html#solutions" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="parameters-of-interest" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> 1. Parameters of Interest<a href="solutions.html#parameters-of-interest" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The parameter of interest is <span class="math inline">\(\theta\)</span>, the probability that a student answers a question correctly.</p>
</div>
<div id="likelihood" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> 2. Likelihood<a href="solutions.html#likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The likelihood is based on the Binomial distribution:</p>
<p><span class="math display">\[
P(X | \theta, n) = \binom{n}{X} \theta^X (1 - \theta)^{n - X},
\]</span></p>
<p>where <span class="math inline">\(X\)</span> is the number of correct answers, <span class="math inline">\(n\)</span> is the total number of questions, and <span class="math inline">\(\theta\)</span> is the probability of answering a question correctly.</p>
</div>
<div id="prior" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> 3. Prior<a href="solutions.html#prior" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We use a Beta prior for <span class="math inline">\(\theta\)</span>, <span class="math inline">\(\text{Beta}(\alpha, \beta)\)</span>, since it is the conjugate prior for the Binomial distribution. For this example, we use a uniform prior: <span class="math inline">\(\text{Beta}(1, 1)\)</span>.</p>
<div id="types-of-priors" class="section level3 hasAnchor" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> 2. Types of Priors<a href="solutions.html#types-of-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Uninformative Prior:</strong>
<ul>
<li>Use this when you have no strong prior beliefs.<br />
</li>
<li>Example: <span class="math inline">\(\text{Beta}(1, 1)\)</span> (uniform prior) assumes all values of <span class="math inline">\(\theta\)</span> between 0 and 1 are equally likely.<br />
</li>
<li>Suitable when you’re starting with minimal assumptions.</li>
</ul></li>
<li><strong>Informative Prior:</strong>
<ul>
<li>Use this when you have prior knowledge or strong assumptions about student performance.<br />
</li>
<li>Example: If you know most students do better than guessing but rarely score perfectly, a <span class="math inline">\(\text{Beta}(a, b)\)</span> with <span class="math inline">\(a &gt; b\)</span> (e.g., <span class="math inline">\(\text{Beta}(2, 1)\)</span>) puts more weight on higher probabilities.</li>
</ul></li>
<li><strong>Weakly Informative Prior:</strong>
<ul>
<li>Use this when you have mild beliefs but don’t want the prior to dominate the data.<br />
</li>
<li>Example: A <span class="math inline">\(\text{Beta}(2, 2)\)</span> prior is symmetric but places less weight on extreme values (near 0 or 1).</li>
</ul></li>
</ul>
</div>
<div id="the-conjugate-prior-is-a-beta-prior.-plot-the-density-with-dbeta." class="section level3 hasAnchor" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> The conjugate prior is a beta prior. Plot the density with dbeta.<a href="solutions.html#the-conjugate-prior-is-a-beta-prior.-plot-the-density-with-dbeta." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="solutions.html#cb13-1" tabindex="-1"></a>theta<span class="ot">=</span><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>,<span class="at">to=</span><span class="dv">1</span>,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb13-2"><a href="solutions.html#cb13-2" tabindex="-1"></a><span class="fu">plot</span>(theta,<span class="fu">dbeta</span>(theta,<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="solutions.html#cb14-1" tabindex="-1"></a><span class="fu">plot</span>(theta,<span class="fu">dbeta</span>(theta,<span class="dv">4</span>,<span class="dv">2</span>),<span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="solutions.html#cb15-1" tabindex="-1"></a><span class="fu">plot</span>(theta,<span class="fu">dbeta</span>(theta,<span class="dv">8</span>,<span class="dv">4</span>),<span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
</div>
</div>
<div id="prior-probabilities" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> 4. Prior Probabilities<a href="solutions.html#prior-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The prior probability calculations are as follows:</p>
<ul>
<li><span class="math inline">\(P(\theta &gt; 0.25)\)</span>:</li>
<li><span class="math inline">\(P(\theta &gt; 0.5)\)</span>:</li>
<li><span class="math inline">\(P(\theta &gt; 0.8)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="solutions.html#cb16-1" tabindex="-1"></a><span class="co"># Calculate prior probabilities</span></span>
<span id="cb16-2"><a href="solutions.html#cb16-2" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.25</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="co"># P(theta &gt; 0.25)</span></span></code></pre></div>
<pre><code>## [1] 0.75</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="solutions.html#cb18-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># P(theta &gt; 0.5)</span></span></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="solutions.html#cb20-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.8</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># P(theta &gt; 0.8)</span></span></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="solutions.html#cb22-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.25</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="co"># P(theta &gt; 0.25)</span></span></code></pre></div>
<pre><code>## [1] 0.9988117</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="solutions.html#cb24-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.5</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># P(theta &gt; 0.5)</span></span></code></pre></div>
<pre><code>## [1] 0.8867188</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="solutions.html#cb26-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.8</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># P(theta &gt; 0.8)</span></span></code></pre></div>
<pre><code>## [1] 0.1611392</code></pre>
<div id="probabilities-and-their-meanings" class="section level3 hasAnchor" number="9.4.1">
<h3><span class="header-section-number">9.4.1</span> Probabilities and Their Meanings<a href="solutions.html#probabilities-and-their-meanings" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong><span class="math inline">\(P(\theta &gt; 0.25) = 0.9988117\)</span>:</strong><br />
There is a 99.88% chance that the student’s ability <span class="math inline">\(\theta\)</span> is greater than 0.25.
<ul>
<li>This means we are almost certain that the student is performing better than random guessing (answering correctly more than 25% of the time).</li>
</ul></li>
<li><strong><span class="math inline">\(P(\theta &gt; 0.5) = 0.8867188\)</span>:</strong><br />
There is an 88.67% chance that the student’s ability <span class="math inline">\(\theta\)</span> is greater than 0.5.
<ul>
<li>This suggests the student is very likely to be answering more than half of the questions correctly.</li>
</ul></li>
<li><strong><span class="math inline">\(P(\theta &gt; 0.8) = 0.1611392\)</span>:</strong><br />
There is only a 16.11% chance that the student’s ability <span class="math inline">\(\theta\)</span> is greater than 0.8.
<ul>
<li>This means it is unlikely that the student is consistently answering 80% or more of the questions correctly, suggesting that their performance is good but not near perfection.</li>
</ul></li>
</ol>
</div>
<div id="summary-1" class="section level3 hasAnchor" number="9.4.2">
<h3><span class="header-section-number">9.4.2</span> Summary<a href="solutions.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Based on these probabilities:
- It’s almost certain that the student is doing better than just guessing.<br />
- They are very likely to answer more than half the questions correctly.<br />
- It is less likely that they are performing exceptionally well, such as scoring 80% or higher.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="solutions.html#cb28-1" tabindex="-1"></a><span class="co"># Posterior parameters</span></span>
<span id="cb28-2"><a href="solutions.html#cb28-2" tabindex="-1"></a>alpha1 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">33</span></span>
<span id="cb28-3"><a href="solutions.html#cb28-3" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">40</span> <span class="sc">-</span> <span class="dv">33</span></span>
<span id="cb28-4"><a href="solutions.html#cb28-4" tabindex="-1"></a></span>
<span id="cb28-5"><a href="solutions.html#cb28-5" tabindex="-1"></a><span class="co"># Posterior probabilities</span></span>
<span id="cb28-6"><a href="solutions.html#cb28-6" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.25</span>, alpha1, beta1, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="solutions.html#cb30-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.5</span>, alpha1, beta1, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9999873</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="solutions.html#cb32-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.8</span>, alpha1, beta1, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.593105</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="solutions.html#cb34-1" tabindex="-1"></a><span class="co"># plot posterior first to get the right scale on the y-axis</span></span>
<span id="cb34-2"><a href="solutions.html#cb34-2" tabindex="-1"></a><span class="fu">plot</span>(theta,<span class="fu">dbeta</span>(theta,<span class="dv">41</span>,<span class="dv">11</span>),<span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb34-3"><a href="solutions.html#cb34-3" tabindex="-1"></a><span class="fu">lines</span>(theta,<span class="fu">dbeta</span>(theta,<span class="dv">8</span>,<span class="dv">4</span>),<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb34-4"><a href="solutions.html#cb34-4" tabindex="-1"></a><span class="co"># plot likelihood</span></span>
<span id="cb34-5"><a href="solutions.html#cb34-5" tabindex="-1"></a><span class="fu">lines</span>(theta,<span class="fu">dbinom</span>(<span class="dv">33</span>,<span class="at">size=</span><span class="dv">40</span>,<span class="at">p=</span>theta),<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb34-6"><a href="solutions.html#cb34-6" tabindex="-1"></a><span class="co"># plot scaled likelihood</span></span>
<span id="cb34-7"><a href="solutions.html#cb34-7" tabindex="-1"></a><span class="fu">lines</span>(theta,<span class="dv">44</span><span class="sc">*</span><span class="fu">dbinom</span>(<span class="dv">33</span>,<span class="at">size=</span><span class="dv">40</span>,<span class="at">p=</span>theta),<span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="solutions.html#cb35-1" tabindex="-1"></a><span class="co"># Credible interval</span></span>
<span id="cb35-2"><a href="solutions.html#cb35-2" tabindex="-1"></a><span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), alpha1, beta1)</span></code></pre></div>
<pre><code>## [1] 0.6794391 0.9117939</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="solutions.html#cb37-1" tabindex="-1"></a><span class="co"># Posterior parameters</span></span>
<span id="cb37-2"><a href="solutions.html#cb37-2" tabindex="-1"></a>alpha2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">24</span></span>
<span id="cb37-3"><a href="solutions.html#cb37-3" tabindex="-1"></a>beta2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">40</span> <span class="sc">-</span> <span class="dv">24</span></span>
<span id="cb37-4"><a href="solutions.html#cb37-4" tabindex="-1"></a></span>
<span id="cb37-5"><a href="solutions.html#cb37-5" tabindex="-1"></a><span class="co"># Posterior probabilities</span></span>
<span id="cb37-6"><a href="solutions.html#cb37-6" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.25</span>, alpha2, beta2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9999989</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="solutions.html#cb39-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.5</span>, alpha2, beta2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.8944882</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="solutions.html#cb41-1" tabindex="-1"></a><span class="fu">pbeta</span>(<span class="fl">0.8</span>, alpha2, beta2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.001380055</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="solutions.html#cb43-1" tabindex="-1"></a><span class="co"># Credible interval</span></span>
<span id="cb43-2"><a href="solutions.html#cb43-2" tabindex="-1"></a><span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), alpha2, beta2)</span></code></pre></div>
<pre><code>## [1] 0.4450478 0.7368320</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="solutions.html#cb45-1" tabindex="-1"></a><span class="co"># Simulate posterior distributions</span></span>
<span id="cb45-2"><a href="solutions.html#cb45-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb45-3"><a href="solutions.html#cb45-3" tabindex="-1"></a>posterior1 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">10000</span>, alpha1, beta1)</span>
<span id="cb45-4"><a href="solutions.html#cb45-4" tabindex="-1"></a>posterior2 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">10000</span>, alpha2, beta2)</span>
<span id="cb45-5"><a href="solutions.html#cb45-5" tabindex="-1"></a></span>
<span id="cb45-6"><a href="solutions.html#cb45-6" tabindex="-1"></a><span class="co"># Calculate probability</span></span>
<span id="cb45-7"><a href="solutions.html#cb45-7" tabindex="-1"></a><span class="fu">mean</span>(posterior1 <span class="sc">&gt;</span> posterior2)</span></code></pre></div>
<pre><code>## [1] 0.985</code></pre>
</div>
</div>
<div id="types-of-gamma-priors" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Types of Gamma Priors<a href="solutions.html#types-of-gamma-priors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Gamma priors are categorized based on their informativeness and the context of their use. This document explains the main types of Gamma priors and demonstrates their visualization in R.</p>
<div id="non-informative-or-weak-priors" class="section level3 hasAnchor" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> 1. Non-Informative or Weak Priors<a href="solutions.html#non-informative-or-weak-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>These priors are used when there is little prior knowledge about the parameter:</p>
<ul>
<li><p><strong>Flat or vague Gamma prior</strong>:<br />
Assigns very small values to shape (<span class="math inline">\(\alpha\)</span>) and rate (<span class="math inline">\(\beta\)</span>), such as <span class="math inline">\(\text{Gamma}(0.001, 0.001)\)</span>. This results in a broad, nearly flat prior.</p></li>
<li><p><strong>Jeffreys prior</strong>:<br />
For scale parameters, Jeffreys prior may take the form <span class="math inline">\(\text{Gamma}(\frac{1}{2}, 0)\)</span>, ensuring minimal prior influence.</p></li>
</ul>
</div>
<div id="informative-priors" class="section level3 hasAnchor" number="9.5.2">
<h3><span class="header-section-number">9.5.2</span> 2. Informative Priors<a href="solutions.html#informative-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Incorporate strong prior beliefs based on historical data or expert knowledge:</p>
<ul>
<li><strong>Concentrated Gamma prior</strong>:<br />
Uses larger <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> values to create a narrow distribution around a specific mean.<br />
Example: <span class="math inline">\(\text{Gamma}(10, 2)\)</span>, with a mean of 5 and variance of 2.5.</li>
</ul>
</div>
<div id="weakly-informative-priors" class="section level3 hasAnchor" number="9.5.3">
<h3><span class="header-section-number">9.5.3</span> 3. Weakly Informative Priors<a href="solutions.html#weakly-informative-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>These priors provide moderate guidance without being overly restrictive:</p>
<ul>
<li><strong>Moderate Gamma prior</strong>:<br />
Example: <span class="math inline">\(\text{Gamma}(2, 1)\)</span>, with a mean of 2 and variance of 2.</li>
</ul>
</div>
<div id="hierarchical-priors" class="section level3 hasAnchor" number="9.5.4">
<h3><span class="header-section-number">9.5.4</span> 4. Hierarchical Priors<a href="solutions.html#hierarchical-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Used as hyperpriors in hierarchical models:</p>
<ul>
<li><strong>Gamma hyperprior</strong>:<br />
Often applied to variances or precisions in hierarchical Bayesian models.</li>
</ul>
</div>
<div id="empirical-priors" class="section level3 hasAnchor" number="9.5.5">
<h3><span class="header-section-number">9.5.5</span> 5. Empirical Priors<a href="solutions.html#empirical-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Derived from observed data or related datasets:</p>
<ul>
<li><strong>Data-driven Gamma prior</strong>:<br />
Parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are estimated based on historical information.</li>
</ul>
</div>
<div id="special-case-priors" class="section level3 hasAnchor" number="9.5.6">
<h3><span class="header-section-number">9.5.6</span> 6. Special Case Priors<a href="solutions.html#special-case-priors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Conjugate Gamma prior</strong>:<br />
Often paired with Poisson or Exponential likelihoods for computational simplicity.</li>
</ul>
</div>
</div>
<div id="visualizing-gamma-priors-in-r" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Visualizing Gamma Priors in R<a href="solutions.html#visualizing-gamma-priors-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The code below demonstrates how to visualize different types of Gamma priors.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="solutions.html#cb47-1" tabindex="-1"></a><span class="co"># Visualization of Gamma Priors</span></span>
<span id="cb47-2"><a href="solutions.html#cb47-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb47-3"><a href="solutions.html#cb47-3" tabindex="-1"></a></span>
<span id="cb47-4"><a href="solutions.html#cb47-4" tabindex="-1"></a><span class="co"># Non-informative prior</span></span>
<span id="cb47-5"><a href="solutions.html#cb47-5" tabindex="-1"></a>gamma_flat <span class="ot">&lt;-</span> <span class="fu">dgamma</span>(x, <span class="at">shape =</span> <span class="fl">0.001</span>, <span class="at">rate =</span> <span class="fl">0.001</span>)</span>
<span id="cb47-6"><a href="solutions.html#cb47-6" tabindex="-1"></a></span>
<span id="cb47-7"><a href="solutions.html#cb47-7" tabindex="-1"></a><span class="co"># Informative prior</span></span>
<span id="cb47-8"><a href="solutions.html#cb47-8" tabindex="-1"></a>gamma_informative <span class="ot">&lt;-</span> <span class="fu">dgamma</span>(x, <span class="at">shape =</span> <span class="dv">10</span>, <span class="at">rate =</span> <span class="dv">2</span>)</span>
<span id="cb47-9"><a href="solutions.html#cb47-9" tabindex="-1"></a></span>
<span id="cb47-10"><a href="solutions.html#cb47-10" tabindex="-1"></a><span class="co"># Weakly informative prior</span></span>
<span id="cb47-11"><a href="solutions.html#cb47-11" tabindex="-1"></a>gamma_weak <span class="ot">&lt;-</span> <span class="fu">dgamma</span>(x, <span class="at">shape =</span> <span class="dv">2</span>, <span class="at">rate =</span> <span class="dv">1</span>)</span>
<span id="cb47-12"><a href="solutions.html#cb47-12" tabindex="-1"></a></span>
<span id="cb47-13"><a href="solutions.html#cb47-13" tabindex="-1"></a><span class="co"># Plot the priors</span></span>
<span id="cb47-14"><a href="solutions.html#cb47-14" tabindex="-1"></a><span class="fu">plot</span>(x, gamma_flat, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb47-15"><a href="solutions.html#cb47-15" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(gamma_informative)),</span>
<span id="cb47-16"><a href="solutions.html#cb47-16" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Parameter Value&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb47-17"><a href="solutions.html#cb47-17" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Types of Gamma Priors&quot;</span>)</span>
<span id="cb47-18"><a href="solutions.html#cb47-18" tabindex="-1"></a><span class="fu">lines</span>(x, gamma_informative, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb47-19"><a href="solutions.html#cb47-19" tabindex="-1"></a><span class="fu">lines</span>(x, gamma_weak, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb47-20"><a href="solutions.html#cb47-20" tabindex="-1"></a></span>
<span id="cb47-21"><a href="solutions.html#cb47-21" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Non-Informative&quot;</span>, <span class="st">&quot;Informative&quot;</span>, <span class="st">&quot;Weakly Informative&quot;</span>),</span>
<span id="cb47-22"><a href="solutions.html#cb47-22" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;green&quot;</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="example-2-gamma-distribution---modeling-call-center-wait-times" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Example 2: Gamma Distribution - Modeling Call Center Wait Times<a href="solutions.html#example-2-gamma-distribution---modeling-call-center-wait-times" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="scenario" class="section level3 hasAnchor" number="9.7.1">
<h3><span class="header-section-number">9.7.1</span> Scenario<a href="solutions.html#scenario" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A call center manager wants to analyze the average wait time for customer service calls. From past experience, the manager believes that the wait time (in minutes) can be modeled as an exponential distribution, which is parameterized by the rate <span class="math inline">\(\lambda\)</span> (calls per minute). To refine this model, the manager uses a Gamma prior for <span class="math inline">\(\lambda\)</span>, and based on data from 20 calls, finds the total wait time is 50 minutes.</p>
<p>Questions:</p>
<ol style="list-style-type: decimal">
<li>What is the posterior distribution of <span class="math inline">\(\lambda\)</span>?</li>
<li>What is the posterior mean of <span class="math inline">\(\lambda\)</span>?</li>
<li>What is a 95% credible interval for <span class="math inline">\(\lambda\)</span>?</li>
</ol>
</div>
</div>
<div id="gamma-distribution-modeling-call-center-wait-times" class="section level2 hasAnchor" number="9.8">
<h2><span class="header-section-number">9.8</span> Gamma Distribution: Modeling Call Center Wait Times<a href="solutions.html#gamma-distribution-modeling-call-center-wait-times" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="problem-description" class="section level3 hasAnchor" number="9.8.1">
<h3><span class="header-section-number">9.8.1</span> Problem Description<a href="solutions.html#problem-description" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We aim to estimate the rate parameter <span class="math inline">\(\lambda\)</span> of an exponential distribution modeling call center wait times. The prior for <span class="math inline">\(\lambda\)</span> is Gamma-distributed with <span class="math inline">\(\text{Gamma}(\alpha = 2, \beta = 1)\)</span>. Given the observed data (total wait time = 50 minutes for 20 calls), we compute the posterior distribution.</p>
</div>
<div id="solution-2" class="section level3 hasAnchor" number="9.8.2">
<h3><span class="header-section-number">9.8.2</span> Solution<a href="solutions.html#solution-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="step-1-posterior-distribution" class="section level4 hasAnchor" number="9.8.2.1">
<h4><span class="header-section-number">9.8.2.1</span> Step 1: Posterior Distribution<a href="solutions.html#step-1-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Using the conjugate prior relationship, the posterior distribution for <span class="math inline">\(\lambda\)</span> is:
<span class="math display">\[
\lambda | \text{data} \sim \text{Gamma}(\alpha + n, \beta + \text{total wait time}),
\]</span>
where <span class="math inline">\(n = 20\)</span> (number of calls) and total wait time = 50 minutes.</p>
</div>
<div id="step-2-calculate-posterior-parameters" class="section level4 hasAnchor" number="9.8.2.2">
<h4><span class="header-section-number">9.8.2.2</span> Step 2: Calculate Posterior Parameters<a href="solutions.html#step-2-calculate-posterior-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="solutions.html#cb48-1" tabindex="-1"></a><span class="co"># Prior parameters</span></span>
<span id="cb48-2"><a href="solutions.html#cb48-2" tabindex="-1"></a>alpha_prior <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb48-3"><a href="solutions.html#cb48-3" tabindex="-1"></a>beta_prior <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb48-4"><a href="solutions.html#cb48-4" tabindex="-1"></a></span>
<span id="cb48-5"><a href="solutions.html#cb48-5" tabindex="-1"></a><span class="co"># Data</span></span>
<span id="cb48-6"><a href="solutions.html#cb48-6" tabindex="-1"></a>n_calls <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb48-7"><a href="solutions.html#cb48-7" tabindex="-1"></a>total_wait_time <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb48-8"><a href="solutions.html#cb48-8" tabindex="-1"></a></span>
<span id="cb48-9"><a href="solutions.html#cb48-9" tabindex="-1"></a><span class="co"># Posterior parameters</span></span>
<span id="cb48-10"><a href="solutions.html#cb48-10" tabindex="-1"></a>alpha_posterior <span class="ot">&lt;-</span> alpha_prior <span class="sc">+</span> n_calls</span>
<span id="cb48-11"><a href="solutions.html#cb48-11" tabindex="-1"></a>beta_posterior <span class="ot">&lt;-</span> beta_prior <span class="sc">+</span> total_wait_time</span>
<span id="cb48-12"><a href="solutions.html#cb48-12" tabindex="-1"></a></span>
<span id="cb48-13"><a href="solutions.html#cb48-13" tabindex="-1"></a>alpha_posterior</span></code></pre></div>
<pre><code>## [1] 22</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="solutions.html#cb50-1" tabindex="-1"></a>beta_posterior</span></code></pre></div>
<pre><code>## [1] 51</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="solutions.html#cb52-1" tabindex="-1"></a>posterior_mean <span class="ot">&lt;-</span> alpha_posterior <span class="sc">/</span> beta_posterior</span>
<span id="cb52-2"><a href="solutions.html#cb52-2" tabindex="-1"></a>posterior_mean</span></code></pre></div>
<pre><code>## [1] 0.4313725</code></pre>
</div>
<div id="step-4-95-credible-interval" class="section level4 hasAnchor" number="9.8.2.3">
<h4><span class="header-section-number">9.8.2.3</span> Step 4: 95% Credible Interval<a href="solutions.html#step-4-95-credible-interval" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The 95% credible interval for <span class="math inline">\(\lambda\)</span> can be calculated using the quantiles of the Gamma distribution:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="solutions.html#cb54-1" tabindex="-1"></a>credible_interval <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">shape =</span> alpha_posterior, <span class="at">rate =</span> beta_posterior)</span>
<span id="cb54-2"><a href="solutions.html#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="solutions.html#cb54-3" tabindex="-1"></a>credible_interval</span></code></pre></div>
<pre><code>## [1] 0.2703389 0.6294261</code></pre>
</div>
</div>
</div>
<div id="example-2-normal-distribution---analyzing-employee-productivity" class="section level2 hasAnchor" number="9.9">
<h2><span class="header-section-number">9.9</span> Example 2: Normal Distribution - Analyzing Employee Productivity<a href="solutions.html#example-2-normal-distribution---analyzing-employee-productivity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A company tracks the daily productivity of its employees in terms of completed tasks. Historically, productivity is normally distributed with an unknown mean <span class="math inline">\(\mu\)</span> and known variance <span class="math inline">\(\sigma^2 = 25\)</span>. From a random sample of 15 employees, the average number of tasks completed is 20. Assume a normal prior for <span class="math inline">\(\mu\)</span> with mean <span class="math inline">\(\mu_0 = 18\)</span> and variance <span class="math inline">\(\tau^2 = 4\)</span>.</p>
<div id="questions" class="section level3 hasAnchor" number="9.9.1">
<h3><span class="header-section-number">9.9.1</span> Questions<a href="solutions.html#questions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What is the posterior distribution of <span class="math inline">\(\mu\)</span>?</li>
<li>What is the posterior mean of <span class="math inline">\(\mu\)</span>?</li>
<li>What is a 95% credible interval for <span class="math inline">\(\mu\)</span>?</li>
</ol>
</div>
</div>
<div id="solution-3" class="section level2 hasAnchor" number="9.10">
<h2><span class="header-section-number">9.10</span> Solution<a href="solutions.html#solution-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="step-1-posterior-distribution-1" class="section level3 hasAnchor" number="9.10.1">
<h3><span class="header-section-number">9.10.1</span> Step 1: Posterior Distribution<a href="solutions.html#step-1-posterior-distribution-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The posterior distribution for <span class="math inline">\(\mu\)</span> is:
<span class="math display">\[
\mu | \text{data} \sim \text{Normal}(\mu_{\text{posterior}}, \tau^2_{\text{posterior}})
\]</span>
where:
<span class="math display">\[
\mu_{\text{posterior}} = \frac{\frac{\mu_0}{\tau^2} + \frac{\bar{x}}{\sigma^2 / n}}{\frac{1}{\tau^2} + \frac{1}{\sigma^2 / n}}, \quad \tau^2_{\text{posterior}} = \frac{1}{\frac{1}{\tau^2} + \frac{1}{\sigma^2 / n}}
\]</span></p>
</div>
<div id="step-2-r-code-to-compute-posterior-parameters" class="section level3 hasAnchor" number="9.10.2">
<h3><span class="header-section-number">9.10.2</span> Step 2: R Code to Compute Posterior Parameters<a href="solutions.html#step-2-r-code-to-compute-posterior-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="solutions.html#cb56-1" tabindex="-1"></a><span class="co"># Prior parameters</span></span>
<span id="cb56-2"><a href="solutions.html#cb56-2" tabindex="-1"></a>mu_prior <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb56-3"><a href="solutions.html#cb56-3" tabindex="-1"></a>tau2_prior <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb56-4"><a href="solutions.html#cb56-4" tabindex="-1"></a></span>
<span id="cb56-5"><a href="solutions.html#cb56-5" tabindex="-1"></a><span class="co"># Data</span></span>
<span id="cb56-6"><a href="solutions.html#cb56-6" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb56-7"><a href="solutions.html#cb56-7" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb56-8"><a href="solutions.html#cb56-8" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb56-9"><a href="solutions.html#cb56-9" tabindex="-1"></a></span>
<span id="cb56-10"><a href="solutions.html#cb56-10" tabindex="-1"></a><span class="co"># Posterior calculations</span></span>
<span id="cb56-11"><a href="solutions.html#cb56-11" tabindex="-1"></a>tau2_posterior <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">/</span> tau2_prior <span class="sc">+</span> n <span class="sc">/</span> sigma2)</span>
<span id="cb56-12"><a href="solutions.html#cb56-12" tabindex="-1"></a>mu_posterior <span class="ot">&lt;-</span> tau2_posterior <span class="sc">*</span> (mu_prior <span class="sc">/</span> tau2_prior <span class="sc">+</span> n <span class="sc">*</span> x_bar <span class="sc">/</span> sigma2)</span>
<span id="cb56-13"><a href="solutions.html#cb56-13" tabindex="-1"></a></span>
<span id="cb56-14"><a href="solutions.html#cb56-14" tabindex="-1"></a>mu_posterior</span></code></pre></div>
<pre><code>## [1] 19.41176</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="solutions.html#cb58-1" tabindex="-1"></a>tau2_posterior</span></code></pre></div>
<pre><code>## [1] 1.176471</code></pre>
<div id="step-3-posterior-mean" class="section level4 hasAnchor" number="9.10.2.1">
<h4><span class="header-section-number">9.10.2.1</span> Step 3: Posterior Mean<a href="solutions.html#step-3-posterior-mean" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The posterior mean <span class="math inline">\(\mu_{\text{posterior}}\)</span> is already calculated above.</p>
</div>
<div id="step-4-95-credible-interval-1" class="section level4 hasAnchor" number="9.10.2.2">
<h4><span class="header-section-number">9.10.2.2</span> Step 4: 95% Credible Interval<a href="solutions.html#step-4-95-credible-interval-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The 95% credible interval for <span class="math inline">\(\mu\)</span> is calculated using the quantiles of the posterior normal distribution.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="solutions.html#cb60-1" tabindex="-1"></a><span class="co"># Compute credible interval</span></span>
<span id="cb60-2"><a href="solutions.html#cb60-2" tabindex="-1"></a>credible_interval <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">mean =</span> mu_posterior, <span class="at">sd =</span> <span class="fu">sqrt</span>(tau2_posterior))</span>
<span id="cb60-3"><a href="solutions.html#cb60-3" tabindex="-1"></a>credible_interval</span></code></pre></div>
<pre><code>## [1] 17.28589 21.53764</code></pre>
</div>
</div>
</div>
<div id="linear-regression" class="section level2 hasAnchor" number="9.11">
<h2><span class="header-section-number">9.11</span> Linear regression<a href="solutions.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Linear regression is a widely used statistical technique for modeling relationships between variables. In the Bayesian framework, linear regression is viewed through the lens of probability, where we incorporate prior beliefs about the model parameters and update these beliefs with observed data using Bayes’ theorem.</p>
<div id="classical-vs.-bayesian-linear-regression" class="section level3 hasAnchor" number="9.11.1">
<h3><span class="header-section-number">9.11.1</span> Classical vs. Bayesian Linear Regression<a href="solutions.html#classical-vs.-bayesian-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Classical Approach</strong>: Parameters are estimated as fixed quantities using techniques like least squares or maximum likelihood estimation.</p></li>
<li><p><strong>Bayesian Approach</strong>: Parameters are treated as random variables with probability distributions. The goal is to determine the posterior distribution of these parameters given the observed data.</p></li>
</ul>
</div>
</div>
<div id="bayesian-linear-regression-framework" class="section level2 hasAnchor" number="9.12">
<h2><span class="header-section-number">9.12</span> Bayesian Linear Regression Framework<a href="solutions.html#bayesian-linear-regression-framework" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="model-specification" class="section level3 hasAnchor" number="9.12.1">
<h3><span class="header-section-number">9.12.1</span> Model Specification<a href="solutions.html#model-specification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Assume a simple linear regression model:
<span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i, \quad \epsilon_i \sim \mathcal{N}(0, \sigma^2)
\]</span>
where:
- <span class="math inline">\(y_i\)</span> is the response variable,
- <span class="math inline">\(x_i\)</span> is the predictor,
- <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the regression coefficients,
- <span class="math inline">\(\epsilon_i\)</span> represents the residuals, assumed to be normally distributed with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p>In matrix form, this becomes:
<span class="math display">\[
\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\epsilon}
\]</span>
where:
- <span class="math inline">\(\mathbf{y}\)</span> is the <span class="math inline">\(n \times 1\)</span> vector of responses,
- <span class="math inline">\(\mathbf{X}\)</span> is the <span class="math inline">\(n \times p\)</span> design matrix,
- <span class="math inline">\(\boldsymbol{\beta}\)</span> is the <span class="math inline">\(p \times 1\)</span> vector of regression coefficients,
- <span class="math inline">\(\boldsymbol{\epsilon} \sim \mathcal{N}(\mathbf{0}, \sigma^2 \mathbf{I})\)</span>.</p>
</div>
<div id="bayesian-framework-1" class="section level3 hasAnchor" number="9.12.2">
<h3><span class="header-section-number">9.12.2</span> Bayesian Framework<a href="solutions.html#bayesian-framework-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p><strong>Prior Distribution</strong>:
Specify prior beliefs about the parameters. For simplicity, assume:
<span class="math display">\[
\boldsymbol{\beta} \sim \mathcal{N}(\boldsymbol{\beta}_0, \boldsymbol{\Sigma}_0), \quad \sigma^2 \sim \text{Inverse-Gamma}(a, b)
  \]</span></p></li>
<li><p><strong>Likelihood</strong>:
The likelihood is derived from the assumed normal distribution of the residuals:
<span class="math display">\[
p(\mathbf{y} | \boldsymbol{\beta}, \sigma^2) = \prod_{i=1}^n \mathcal{N}(y_i | \mathbf{x}_i^\top \boldsymbol{\beta}, \sigma^2)
\]</span></p></li>
<li><p><strong>Posterior Distribution</strong>:
Combine the prior and likelihood using Bayes’ theorem:
<span class="math display">\[
p(\boldsymbol{\beta}, \sigma^2 | \mathbf{y}) \propto p(\mathbf{y} | \boldsymbol{\beta}, \sigma^2) p(\boldsymbol{\beta}) p(\sigma^2)
\]</span></p></li>
</ol>
</div>
</div>
<div id="example-bayesian-linear-regression-in-r" class="section level2 hasAnchor" number="9.13">
<h2><span class="header-section-number">9.13</span> Example: Bayesian Linear Regression in R<a href="solutions.html#example-bayesian-linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="problem-setup" class="section level3 hasAnchor" number="9.13.1">
<h3><span class="header-section-number">9.13.1</span> Problem Setup<a href="solutions.html#problem-setup" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we have data on house prices (<span class="math inline">\(y\)</span>) and square footage (<span class="math inline">\(x\)</span>), and we want to model the relationship using Bayesian linear regression.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="solutions.html#cb62-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb62-2"><a href="solutions.html#cb62-2" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span></code></pre></div>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## This is rstanarm version 2.32.1</code></pre>
<pre><code>## - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!</code></pre>
<pre><code>## - Default priors may change, so it&#39;s safest to specify priors, even if equivalent to the defaults.</code></pre>
<pre><code>## - For execution on a local, multicore CPU with excess RAM we recommend calling</code></pre>
<pre><code>##   options(mc.cores = parallel::detectCores())</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="solutions.html#cb69-1" tabindex="-1"></a><span class="co"># Simulated data</span></span>
<span id="cb69-2"><a href="solutions.html#cb69-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb69-3"><a href="solutions.html#cb69-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb69-4"><a href="solutions.html#cb69-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">500</span>, <span class="dv">3000</span>) <span class="co"># Square footage</span></span>
<span id="cb69-5"><a href="solutions.html#cb69-5" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">50</span> <span class="sc">+</span> <span class="fl">0.1</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">25</span>) <span class="co"># House prices</span></span>
<span id="cb69-6"><a href="solutions.html#cb69-6" tabindex="-1"></a></span>
<span id="cb69-7"><a href="solutions.html#cb69-7" tabindex="-1"></a><span class="co"># Fit Bayesian linear regression</span></span>
<span id="cb69-8"><a href="solutions.html#cb69-8" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(y <span class="sc">~</span> x, <span class="at">prior =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">50</span>, <span class="dv">10</span>), <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">2000</span>)</span></code></pre></div>
<pre><code>## Warning: Omitting the &#39;data&#39; argument is not recommended and may not be allowed
## in future versions of rstanarm. Some post-estimation functions (in particular
## &#39;update&#39;, &#39;loo&#39;, &#39;kfold&#39;) are not guaranteed to work properly unless &#39;data&#39; is
## specified as a data frame.</code></pre>
<pre><code>## 
## SAMPLING FOR MODEL &#39;continuous&#39; NOW (CHAIN 1).
## Chain 1: 
## Chain 1: Gradient evaluation took 0.002028 seconds
## Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 20.28 seconds.
## Chain 1: Adjust your expectations accordingly!
## Chain 1: 
## Chain 1: 
## Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 1: 
## Chain 1:  Elapsed Time: 0.803 seconds (Warm-up)
## Chain 1:                0.128 seconds (Sampling)
## Chain 1:                0.931 seconds (Total)
## Chain 1: 
## 
## SAMPLING FOR MODEL &#39;continuous&#39; NOW (CHAIN 2).
## Chain 2: 
## Chain 2: Gradient evaluation took 2.5e-05 seconds
## Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.25 seconds.
## Chain 2: Adjust your expectations accordingly!
## Chain 2: 
## Chain 2: 
## Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 2: 
## Chain 2:  Elapsed Time: 2.861 seconds (Warm-up)
## Chain 2:                0.08 seconds (Sampling)
## Chain 2:                2.941 seconds (Total)
## Chain 2: 
## 
## SAMPLING FOR MODEL &#39;continuous&#39; NOW (CHAIN 3).
## Chain 3: 
## Chain 3: Gradient evaluation took 1.8e-05 seconds
## Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.18 seconds.
## Chain 3: Adjust your expectations accordingly!
## Chain 3: 
## Chain 3: 
## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 3: 
## Chain 3:  Elapsed Time: 1.045 seconds (Warm-up)
## Chain 3:                0.132 seconds (Sampling)
## Chain 3:                1.177 seconds (Total)
## Chain 3: 
## 
## SAMPLING FOR MODEL &#39;continuous&#39; NOW (CHAIN 4).
## Chain 4: 
## Chain 4: Gradient evaluation took 1.9e-05 seconds
## Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.19 seconds.
## Chain 4: Adjust your expectations accordingly!
## Chain 4: 
## Chain 4: 
## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 4: 
## Chain 4:  Elapsed Time: 2.582 seconds (Warm-up)
## Chain 4:                0.081 seconds (Sampling)
## Chain 4:                2.663 seconds (Total)
## Chain 4:</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="solutions.html#cb72-1" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb72-2"><a href="solutions.html#cb72-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Model Info:
##  function:     stan_glm
##  family:       gaussian [identity]
##  formula:      y ~ x
##  algorithm:    sampling
##  sample:       4000 (posterior sample size)
##  priors:       see help(&#39;prior_summary&#39;)
##  observations: 50
##  predictors:   2
## 
## Estimates:
##               mean   sd     10%    50%    90% 
## (Intercept) -103.6   52.9 -172.0 -104.0  -37.2
## x              0.1    0.0    0.1    0.1    0.1
## sigma        152.5   19.2  129.3  151.2  177.7
## 
## Fit Diagnostics:
##            mean   sd    10%   50%   90%
## mean_PPD  82.9   24.6  51.0  83.8 114.0
## 
## The mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help(&#39;summary.stanreg&#39;)).
## 
## MCMC diagnostics
##               mcse Rhat n_eff
## (Intercept)   0.9  1.0  3445 
## x             0.0  1.0  3763 
## sigma         0.4  1.0  2001 
## mean_PPD      0.4  1.0  3444 
## log-posterior 0.0  1.0  1848 
## 
## For each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).</code></pre>
</div>
<div id="posterior-analysis" class="section level3 hasAnchor" number="9.13.2">
<h3><span class="header-section-number">9.13.2</span> Posterior Analysis<a href="solutions.html#posterior-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The posterior distributions of the parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are estimated using Markov Chain Monte Carlo (MCMC).</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="solutions.html#cb74-1" tabindex="-1"></a><span class="co"># Plot posterior distributions</span></span>
<span id="cb74-2"><a href="solutions.html#cb74-2" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">prob =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## Warning: `prob_outer` (0.9) is less than `prob` (0.95)
## ... Swapping the values of `prob_outer` and `prob`</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
</div>
<div id="interpretation-1" class="section level2 hasAnchor" number="9.14">
<h2><span class="header-section-number">9.14</span> Interpretation<a href="solutions.html#interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><strong>Posterior Mean</strong>: The posterior mean of each parameter represents the updated estimate after observing the data.</li>
<li><strong>Credible Interval</strong>: The 95% credible interval for each parameter provides a range of values within which the parameter lies with 95% probability.</li>
<li><strong>Prediction</strong>: Bayesian regression allows us to make probabilistic predictions for new data points by integrating over the posterior distributions of the parameters.</li>
</ol>
</div>
<div id="advantages-of-bayesian-linear-regression" class="section level2 hasAnchor" number="9.15">
<h2><span class="header-section-number">9.15</span> Advantages of Bayesian Linear Regression<a href="solutions.html#advantages-of-bayesian-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><strong>Incorporation of Prior Knowledge</strong>: Bayesian methods allow for the inclusion of prior beliefs, making them useful when prior information is available.</li>
<li><strong>Uncertainty Quantification</strong>: Bayesian regression provides full distributions for parameters and predictions, not just point estimates.</li>
<li><strong>Flexibility</strong>: The Bayesian framework can handle complex models and adapt to small sample sizes better than classical methods.</li>
</ol>
</div>
<div id="conclusion-2" class="section level2 hasAnchor" number="9.16">
<h2><span class="header-section-number">9.16</span> Conclusion<a href="solutions.html#conclusion-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bayesian linear regression provides a robust framework for understanding relationships between variables while accounting for uncertainty in a principled way. By leveraging prior information and updating beliefs with observed data, this approach offers a powerful alternative to classical regression techniques.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exercise-description.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-pool-of-tears.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/xadex01/Bayesian_Statistics/edit/main/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/xadex01/Bayesian_Statistics/blob/main/index.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
